-- Stage seed data is created by Node scripts because Supabase Auth users and
-- project memberships must be resolved through the service key.
--
-- Run:
--   npm run seed:stage1
--   npm run seed:stage2
